# Generated by Django 3.2.20 on 2023-09-07 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDirection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=200)),
                ('place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='place_truck_direction', to='master.place')),
                ('truck', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='truck_direction', to='master.truck')),
            ],
            options={
                'db_table': 'truck_directions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlaceCompletement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('rest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=200)),
                ('place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='place_completement', to='master.place')),
            ],
            options={
                'db_table': 'place_completements',
                'ordering': ['-id'],
            },
        ),
    ]
