# Generated by Django 3.2.20 on 2023-09-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('transaction', '0002_maintrial_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintrial',
            name='fuel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='main_trial', to='master.fuel'),
        ),
        migrations.AddField(
            model_name='maintrial',
            name='loading_armroll',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='maintrial',
            name='loading_dump',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='maintrial',
            name='unloading_armroll',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='maintrial',
            name='unloading_dump',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='maintrial',
            name='velocity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
