# Generated by Django 3.2.20 on 2023-09-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_truckdirection_takes_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdirection',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
