# Generated by Django 3.2.20 on 2023-09-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('transaction', '0003_auto_20230910_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckhistory',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='truck_history', to='master.trucktype'),
        ),
    ]
