# Generated by Django 3.2.20 on 2023-09-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_truckdirection_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckhistory',
            name='reach_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
